### ISSUE TITLE
Need a way to override the default white bg of options.

### ISSUE THREAD

**Issue by ridays2001** [Codebrahma/React-combobox#6]
https://github.com/Codebrahma/React-combobox/blob/e75647f6a4168bc7ab4ab32855a8a12f14862014/src/index.tsx#L286
This line is a big issue for people who are making dark mode websites. Since it uses inline styles, it's impossible to override without messing up everything else. I had used that, but then the highlight color was messed up. Maybe accept that as a prop?

![image](https://user-images.githubusercontent.com/46166258/136370042-751d5950-3271-42dc-b4f7-0c96396c7c5d.png)

**Comment by wxf-contentgroove** [comment]
I think you might be able to override that using the className option and then css, 

see: https://github.com/Codebrahma/React-combobox/blob/e75647f6a4168bc7ab4ab32855a8a12f14862014/src/index.tsx#L354

otherwise it wouldn't be too hard to hack it to take some extra props.

**Comment by ridays2001** [comment]
ClassName doesn't work. I already tried. Inline CSS takes precedence over classes... So, it won't work.

**Comment by ashwinKumar0505** [comment]
Hai @ridays2001 The issue had been fixed. Now you can use the optionsClassName to style the background colour for the default background colour of options.
